package th.co.krungthaiaxa.elife.api.model.enums;

public enum BeneficiaryRelationshipType {
    AUNT, BROTHER, FIANCE, FIANCEE, GRAND_DAUGHTER, GRAND_SON,
    SISTER, UNCLE, NEPHEW, NIECE, HERITAGE,

    PARENT, SPOUSE, CHILD, SISTER_BROTHER, AUNT_UNCLE, GRAND_PARENT, NEPHEW_NIECE, FIANCE_FIANCEE, ESTATE,
    COUSIN, GUARDIAN, GRANDCHILD, PARENT_IN_LAW
}

