//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:39:05 AM ICT 
//


package th.co.krungthaiaxa.elife.api.tmc.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the th.co.krungthaiaxa.elife.api.tmc.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: th.co.krungthaiaxa.elife.api.tmc.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReceiveDataJSON }
     * 
     */
    public ReceiveDataJSON createReceiveDataJSON() {
        return new ReceiveDataJSON();
    }

    /**
     * Create an instance of {@link ReceiveDataJSONResponse }
     * 
     */
    public ReceiveDataJSONResponse createReceiveDataJSONResponse() {
        return new ReceiveDataJSONResponse();
    }

    /**
     * Create an instance of {@link ReceiveDataJSONIMG }
     * 
     */
    public ReceiveDataJSONIMG createReceiveDataJSONIMG() {
        return new ReceiveDataJSONIMG();
    }

    /**
     * Create an instance of {@link ReceiveDataJSONIMGResponse }
     * 
     */
    public ReceiveDataJSONIMGResponse createReceiveDataJSONIMGResponse() {
        return new ReceiveDataJSONIMGResponse();
    }

    /**
     * Create an instance of {@link ReceiveDataJSONIMGTMC }
     * 
     */
    public ReceiveDataJSONIMGTMC createReceiveDataJSONIMGTMC() {
        return new ReceiveDataJSONIMGTMC();
    }

    /**
     * Create an instance of {@link ReceiveDataJSONIMGTMCResponse }
     * 
     */
    public ReceiveDataJSONIMGTMCResponse createReceiveDataJSONIMGTMCResponse() {
        return new ReceiveDataJSONIMGTMCResponse();
    }

    /**
     * Create an instance of {@link ReceivePDFJSON }
     * 
     */
    public ReceivePDFJSON createReceivePDFJSON() {
        return new ReceivePDFJSON();
    }

    /**
     * Create an instance of {@link ReceivePDFJSONResponse }
     * 
     */
    public ReceivePDFJSONResponse createReceivePDFJSONResponse() {
        return new ReceivePDFJSONResponse();
    }

}
