package th.co.krungthaiaxa.api.elife.model.enums;

public enum BeneficiaryRelationshipType {
	FATHER, MOTHER, SPOUSE, CHILD, OLDER_BRO_SIS, YOUNGER_BRO_SIS, UNCLE, 
	AUNT, UNCLE_AUNT_MOTHER, UNCLE_AUNT_FATHER, GRANDFATHER_FA, GRANDMOTHER_FA, 
	GRANDFATHER_MO, GRANDMOTHER_MO, GRANDSON, FIANCE_FIANCEE
}

