package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.8
 * 2016-04-22T15:04:42.314+07:00
 * Generated source version: 2.4.8
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "WebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WebServiceSoap {

    /**
     * Returns string format Json :  Receive string format Json 
     */
    @WebMethod(operationName = "ReceivePDFJSON", action = "http://tempuri.org/ReceivePDFJSON")
    @RequestWrapper(localName = "ReceivePDFJSON", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReceivePDFJSON")
    @ResponseWrapper(localName = "ReceivePDFJSONResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReceivePDFJSONResponse")
    @WebResult(name = "ReceivePDFJSONResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String receivePDFJSON(
        @WebParam(name = "stringJSON", targetNamespace = "http://tempuri.org/")
        java.lang.String stringJSON
    );

    /**
     * Returns string format Json :  Receive string user,string pass and string format Json 
     */
    @WebMethod(operationName = "ReceiveDataJSON_IMG_TMC", action = "http://tempuri.org/ReceiveDataJSON_IMG_TMC")
    @RequestWrapper(localName = "ReceiveDataJSON_IMG_TMC", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReceiveDataJSONIMGTMC")
    @ResponseWrapper(localName = "ReceiveDataJSON_IMG_TMCResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReceiveDataJSONIMGTMCResponse")
    @WebResult(name = "ReceiveDataJSON_IMG_TMCResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String receiveDataJSONIMGTMC(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        java.lang.String pass,
        @WebParam(name = "stringJSON", targetNamespace = "http://tempuri.org/")
        java.lang.String stringJSON
    );

    /**
     * Returns string format Json :  Receive string format Json 
     */
    @WebMethod(operationName = "ReceiveDataJSON_IMG", action = "http://tempuri.org/ReceiveDataJSON_IMG")
    @RequestWrapper(localName = "ReceiveDataJSON_IMG", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReceiveDataJSONIMG")
    @ResponseWrapper(localName = "ReceiveDataJSON_IMGResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReceiveDataJSONIMGResponse")
    @WebResult(name = "ReceiveDataJSON_IMGResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String receiveDataJSONIMG(
        @WebParam(name = "stringJSON", targetNamespace = "http://tempuri.org/")
        java.lang.String stringJSON
    );

    /**
     * Returns string format Json :  Receive string format Json 
     */
    @WebMethod(operationName = "ReceiveDataJSON", action = "http://tempuri.org/ReceiveDataJSON")
    @RequestWrapper(localName = "ReceiveDataJSON", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReceiveDataJSON")
    @ResponseWrapper(localName = "ReceiveDataJSONResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReceiveDataJSONResponse")
    @WebResult(name = "ReceiveDataJSONResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String receiveDataJSON(
        @WebParam(name = "stringJSON", targetNamespace = "http://tempuri.org/")
        java.lang.String stringJSON
    );
}
